### ISSUE TITLE
Open Menu

### ISSUE THREAD

**Issue by bplrdev** [chipslays/ModMenu#1]
Hi,
Noob here. After I inject the dll it wont open in game by pressing Num1  (e.KeyCode == Keys.NumPad1) I even tried to change it to a different key. What am I doing wrong?

**Comment by chipslays** [comment]
Hi, 
You need:
1. Build dll
2. Put it in the "scripts" folder at the root of the game.
3. Start the game/or if the game is already on, then open the Scripthook console (by default `F4`), and enter the command `Reload()`

Now the your dll will be injected and you can press `Numpad1`

**Comment by chipslays** [comment]
Check it https://youtu.be/8D8xWA1sk-8
I hope it helpful.

**Comment by bplrdev** [comment]
Thank you!
